[alias]
client = "run -p client"
client-log = "make client-log"
client-tracy = "run -p client --features tracy"
server = "run -p server"
server-log = "make server-log"
server-tracy = "run -p server --features tracy"
web = "make web"
setup = "make setup"

# Utility aliases
check-all = "check --workspace"
build-all = "build --workspace --exclude web"
web-build = "build --release -p web --target wasm32-unknown-unknown"
test-all = "make test-all"
test-native = "make test-native"
test-wasm = "make test-wasm"

[build]
incremental = true

[target.wasm32-unknown-unknown]
rustflags = [
  "--cfg",
  "web_sys_unstable_apis",
  "-C",
  "target-feature=+reference-types",
]
